version: '3'
services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - "8089:80"
    depends_on:
      - db
  db:
    image: mysql:8.0
    platform: 
      linux/x86_64 
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - "3380:3306"
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=rootpass
      